# CI de Nivel 01 - Disparo manual atraves de clique

name: 'N1 - Execucao Manual'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    name: Executar testes E2E
    runs-on: ubuntu-latest

    steps:
      - name: Clonando projeto
        uses: actions/checkout@v4

      - name: Instalando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Instalando Browsers do Playwright
        run: yarn playwright install

      - name: Executando testes e2e
        run: yarn run e2e

      - name: Salvando relatorios de testes
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: ./playwright-report
          name: Relatorio de Testes E2E
